#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    contosogw-app:
        image: contosogw
        external_links:
            - contosogw-mariadb:mariadb
            # Uncomment to have Cassandra working with the gateway
            # - contosogw-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/contosogw
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 9000:9000
    contosogw-mariadb:
        extends:
            file: mariadb.yml
            service: contosogw-mariadb
    # Uncomment to have Cassandra working with the gateway
    # contosogw-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: contosogw-cassandra
    # contosogw-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: contosogw-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
